### ISSUE TITLE
Make sdbmigrate friendly for simple projects

### ISSUE THREAD

**Issue by drednout** [wgnet/sdbmigrate#3]
I propose a small set of improvements, which will make sdbmigrate for friendly for projects without sharded DBs, but with heavy schema usage:
1) sharding settings should become optional, by default shard_count may be equal to 1
2) add ability to configure schema to store sdbmigrate state - it's public by default, but sometimes public is not OK
3) ignore files with migrations with suffixes other than py/sql (e.g. vim tmp files break sdbmigrate)
4) add command for generating next empty migration - it's just handy and other migrators have such a simple feature
5) add ability to use sdbmigrate as a module for running with dynamic configs, received from HTTP API

**Comment by grepz** [comment]
Regarding 2: it should be optional, sometimes public access is needed, in case of external scripts.

**Comment by drednout** [comment]
> sharding settings should become optional, by default shard_count may be equal to 1

https://github.com/wgnet/sdbmigrate/commit/8da1231bfb6bbb8a6ca13009f6ada1636ef72b4c

> add ability to configure schema to store sdbmigrate state - it's public by default, but sometimes public is not OK

https://github.com/wgnet/sdbmigrate/commit/1bcdad3a78e83dbf21e32476989bf333863473d5

> add command for generating next empty migration - it's just handy and other migrators have such a simple feature

https://github.com/wgnet/sdbmigrate/commit/dbd23905f3feb1fbf333d14b1a36e58d04b06491
https://github.com/wgnet/sdbmigrate/commit/5cabc94a1ac19116434389e7d0a05f7797ca0a66

> ignore files with migrations with suffixes other than py/sql (e.g. vim tmp files break sdbmigrate)

Won't do because it may causes problems in production environment with silent migration skipping. It will be better to have a small pain during development.

> add ability to use sdbmigrate as a module for running with dynamic configs, received from HTTP API

Will be done in separate ticket. Scope is bigger, e.g. it would be great to make sdbmigrate convenient to use with cloud PostgreSQL, e.g. Neon or AWS. 
=> https://github.com/wgnet/sdbmigrate/issues/5

**Comment by drednout** [comment]
Done, released in version [1.1.0](https://github.com/wgnet/sdbmigrate/tree/1.1.0)
